plugins {
    id 'com.android.application'
}

android {
    namespace 'com.barmadrid.order'
    compileSdk 35

    defaultConfig {
        applicationId 'com.barmadrid.order'
        minSdk 23
        targetSdk 35
        versionCode 10
        versionName '7.3'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
